Clean up Cargo.toml files across workspace
mobilecoinfoundation/mobilecoin pull request #1632
Opened 2022-03-15 16:26 UTC by remoun

With [`cargo-sort`](https://crates.io/crates/cargo-sort). Command: `cargo sort -w --grouped`

2022-03-15 16:34 UTC, eranrund commented on attest/ake/Cargo.toml
> +aes-gcm = "0.9.4"
Looks like there's a missing empty line between our crates and the public ones

2022-03-15 16:38 UTC, eranrund requested changes
Nice. Can you please add it to the lint checker script as well (`./tools/lint.sh`)? It has a `-c` flag for checking and returning a non-zero exit code if there are unsorted files.

2022-03-15 16:38 UTC, eranrund commented on consensus/enclave/impl/Cargo.toml
> +rand = "0.8"
Missing new line to separate ours from public

2022-03-15 16:38 UTC, eranrund commented on crypto/keys/Cargo.toml
>  pem = "1.0"
Missing new line to separate ours from public

2022-03-15 17:14 UTC, garbageslam approved these changes

2022-03-16 17:41 UTC, remoun commented
PTAL, added the check to `lint.sh` and fixed a couple more files.

2022-03-16 17:53 UTC, jcape approved these changes

2022-03-16 21:28 UTC, iamalwaysuncomfortable approved these changes

2022-03-16 22:47 UTC, eranrund approved these changes

2022-03-16 22:48 UTC, merged