Fix/ocall oram storage authentication
mobilecoinfoundation/mobilecoin pull request #1732
Opened 2022-03-30 08:12 UTC by wjuan-mob

This is a clone of [1585](https://github.com/mobilecoinfoundation/mobilecoin/pull/1585)
Adds some naming clarification around the various indices used in the tests.
Fixes the tests by using indices that actually share a trusted merkle root.

2022-03-30 16:11 UTC, jcape requested changes
Could you merge from master, there are quite a few (presumably) unintentional downgrades of packages in this PR.

2022-03-30 16:17 UTC, wjuan-mob commented
> Could you merge from master, there are quite a few (presumably) unintentional downgrades of packages in this PR.

Sorry about that. I had actually rebased to master. Not sure what went wrong here. I'll look at it.

2022-03-30 17:29 UTC, garbageslam approved these changes
LGTM, thank you!

2022-03-30 20:38 UTC, jcape commented
@wjuan-mob LMK when you've gotten the Cargo.lock restored, as of right now every package is updated...

2022-03-31 01:55 UTC, wjuan-mob commented
> @wjuan-mob LMK when you've gotten the Cargo.lock restored, as of right now every dependency is updated...

I'm sorry. I looked into this further and I can not figure out this dependency tree. I tried copying in the cargo.lock from master and rebuilding as suggested, but that just returned me to the previous state with the downgraded dependencies. I'm trying to find some reason that it might be intentionally downgrading the dependencies but I can not find that either.

2022-03-31 02:03 UTC, garbageslam commented
I will take a look

2022-03-31 03:52 UTC, garbageslam commented
i think what was happening was, two things:

because of the merge commit, github was showing a diff that includes all of the changes that were merged from master. this makes the github diff view useless, and shows all the cargo.lock changes from the recent version bumps.

to resolve this, i decided to squash the whole PR. i did this by `git rebase -i master` and squashed every commit into the first one.

i got a conflict like this:

```
diff --cc Cargo.lock
index f6c426bb,b683a64f..00000000
--- a/Cargo.lock
+++ b/Cargo.lock
diff --cc fog/ocall_oram_storage/trusted/Cargo.toml
index 6e9d673a,ac5857fb..00000000
--- a/fog/ocall_oram_storage/trusted/Cargo.toml
+++ b/fog/ocall_oram_storage/trusted/Cargo.toml
@@@ -22,7 -22,11 +22,11 @@@ rand_core = { version = "0.6", default-
  subtle = { version = "2", default-features = false }
  
  [target.'cfg(any(target_feature = "avx2", target_feature = "avx"))'.dependencies]
- blake2 = { version = "0.10.4", default-features = false, features = ["simd"] }
 -blake2 = { version = "0.9.2", default-features = false, features = ["simd"] }
++blake2 = { version = "0.10.2", default-features = false, features = ["simd"] }
  
  [target.'cfg(not(any(target_feature = "avx2", target_feature = "avx")))'.dependencies]
 -blake2 = { version = "0.9.2", default-features = false }
 +blake2 = { version = "0.10.2", default-features = false }
+ 
+ [dev-dependencies]
+ lazy_static = "1.4"
+ mc-util-test-helper = { path = "../../../util/test-helper" }
~
chris@chris-ThinkPad-X1-Carbon-7th:~/mobilecoinofficial/mobilecoin$ git diff
diff --cc Cargo.lock
index f6c426bb,b683a64f..00000000
--- a/Cargo.lock
+++ b/Cargo.lock
diff --cc fog/ocall_oram_storage/trusted/Cargo.toml
index 6e9d673a,ac5857fb..00000000
--- a/fog/ocall_oram_storage/trusted/Cargo.toml
+++ b/fog/ocall_oram_storage/trusted/Cargo.toml
@@@ -22,7 -22,11 +22,11 @@@ rand_core = { version = "0.6", default-
  subtle = { version = "2", default-features = false }
  
  [target.'cfg(any(target_feature = "avx2", target_feature = "avx"))'.dependencies]
- blake2 = { version = "0.10.4", default-features = false, features = ["simd"] }
 -blake2 = { version = "0.9.2", default-features = false, features = ["simd"] }
++blake2 = { version = "0.10.2", default-features = false, features = ["simd"] }
  
  [target.'cfg(not(any(target_feature = "avx2", target_feature = "avx")))'.dependencies]
 -blake2 = { version = "0.9.2", default-features = false }
 +blake2 = { version = "0.10.2", default-features = false }
+ 
+ [dev-dependencies]
+ lazy_static = "1.4"
+ mc-util-test-helper = { path = "../../../util/test-helper" }
```
the left `-` shows ours, the right `-` shows theirs. the `++` shows how I resolved it.
at some point in development we tried to change `blake2` to version `0.10.4` but what I saw when i did `git grep "blake2="` was that all the other crates were settign this to `0.10.2`, so i didn't take ours or theirs, and changed this to use that version.

then i tried a rebuild, to get an up-to-date cargo.lock based on the cargo tomls.

after this i added cargo.lock and continued rebasing. this caused no more cargo lock changes and dropped the last two "update cargo lock" commits.

so i think the moral of the story is:
* merging master into the PR can cause confusing diffs in the github view, especially if there were a lot of version bumps and such in the changes that were merged in
* if you are getting a diff that shows changes that don't make sense (i.e. don't reflect a difference with current master, but an old version of master), then the right thing to do is probably squash the PR. squashing the merge and linearizing history means the reviewers will see a diff with current master rather than an old version of master.

2022-03-31 03:59 UTC, garbageslam commented
@wjuan-mob it may also be that the view was weird because you did the merge in kind of a funky way -- you started by checking out current master, and then made a branch there, and then merged my PR in.

that's backwards from how it's normally done. you should probably have checked out my PR, made a new branch there, and then merged master in if that's what you wanted to do.

merging is not symmetrical, deciding which is "ours" and which is "theirs" affects merge resolution, and may also affect the "view" git has of what the changes are when you look at the diff. so although it may seem counter-intuitive, you will get different results if you merge my PR into master, and then open a PR that merges that into master, from if you merge master into my PR, and then open a PR that merges that branch back into master.

2022-03-31 04:09 UTC, remoun approved these changes

2022-03-31 15:07 UTC, jcape approved these changes

2022-03-31 16:36 UTC, merged