Feature/attest verifier mc seed bugfix
mobilecoinfoundation/mobilecoin pull request #1943
Opened 2022-05-09 01:39 UTC by BrianCorbin

* Attest Verifier now regenerates data/sim/* when a new MC_SEED is provided
* Local Network tool now uses TARGET_DIR for ledger-distribution folders to enable docker volume sharing
### Motivation

We needed this to enable local networks with IAS in DEV simulation mode, which generates a random key for attestation instead of requesting it from Intel, which they won't provide during development.

This was causing issues when using different builds of the attest verifier, because each build would use a different random key while also not regenerating the correct files if they already existed and MC_SEED was present, which should cause them to be regenerated.

### Future Work

[Soundtrack of this PR]()

2022-05-09 17:10 UTC, jcape requested changes
This can just be a call to [`cargo_emit::rerun_if_env_changed("MC_SEED")`](https://docs.rs/cargo-emit/latest/cargo_emit/macro.rerun_if_env_changed.html)

2022-05-09 19:17 UTC, remoun approved these changes

2022-05-09 19:18 UTC, remoun requested changes
Oops, withdrawing approval till James' comment is resolved.

2022-05-09 20:35 UTC, BrianCorbin commented
ahh, can we simply get rid of the conditional of checking if the files exist already and just rely on the cargo_emit messages?

2022-05-09 20:43 UTC, BrianCorbin commented
Honestly, is there any harm in just running this unconditionally every time and not worrying about if it changed since the last build?

2022-05-09 23:16 UTC, jcape approved these changes

2022-05-10 00:26 UTC, iamalwaysuncomfortable approved these changes

2022-05-10 00:34 UTC, eranrund commented on tools/local-network/local_network.py
> +        self.ledger_distribution_dir = os.path.join(TARGET_DIR, f'node-ledger-distribution-{self.node_num}')
Why was this changed?

2022-05-10 03:01 UTC, BrianCorbin commented
@remoun could you redact your change request?

2022-05-10 05:58 UTC, remoun approved these changes

2022-05-10 16:52 UTC, eranrund commented on tools/local-network/local_network.py
> +        self.ledger_distribution_dir = os.path.join(TARGET_DIR, f'node-ledger-distribution-{self.node_num}')
Why is that needed? It it a weird hack to only put one of these things over there and not the others.
It also gets in the way of cleaning up past runs by deleting the work dir.
Why not move the entire work dir under target?

2022-05-10 17:07 UTC, merged