added proper testing for sorted outputs for BlockVersion version 3 an…
mobilecoinfoundation/mobilecoin pull request #2062
Opened 2022-05-27 02:14 UTC by integral-llc

…d higher

### Motivation

needed unit tests for sorted outputs fpr BV > 3

### Future Work

[Soundtrack of this PR]()

2022-05-29 15:00 UTC, garbageslam commented on transaction/core/tests/validation.rs
> +mod tests {
This is normally done for unit tests in a source file, but now, this is a separate tests module at crate level. There's no need to write mod tests here, this file is already entirely tests. So we should just not do this

2022-05-29 15:02 UTC, garbageslam requested changes
Looks fine, but we don't need the `mod tests` that was added

2022-05-31 23:29 UTC, garbageslam approved these changes
Lgtm

2022-06-01 06:58 UTC, remoun approved these changes

2022-06-01 13:44 UTC, merged