Add get shared_secret & root_entropy FFIs to LibMobileCoin
mobilecoinfoundation/mobilecoin pull request #2076
Opened 2022-05-31 19:54 UTC by the-real-adammork

Add getters for shared_secret and root_entropy to LibMobileCoin

### Motivation

Getters are needed for shared_secret, and root_entropy requirements have changed so the removed implementation has been re-added.

[Loose Ends - Lets Wax a Fatty](https://www.youtube.com/watch?v=CBN5c1E8nZI)

2022-06-01 02:23 UTC, voloshyn approved these changes

2022-06-01 02:26 UTC, jcape requested changes
Let's hold off on this until v1.2.1.

2022-06-06 21:16 UTC, the-real-adammork commented
@jcape ok I need one more review

2022-06-06 21:51 UTC, jcape approved these changes

2022-06-06 21:51 UTC, merged