View Account Key
mobilecoinfoundation/mobilecoin pull request #2199
Opened 2022-06-27 16:25 UTC by BrianCorbin

Adding ViewAccountKey struct which stores the view_private_key and spend_public_key, which can be used to generate PublicAddresses using a different derivation path than the current implementation in AccountKey

Current:
![173395537-4f3c246f-8962-43e5-8cad-9fc81ae3b9c9](https://user-images.githubusercontent.com/4346395/175989279-7ec85fdc-5aa0-40cf-bd5a-462e61a9fa55.png)

New:
![173395410-bb207166-9fd8-45d4-b3b9-855d881cbcfa](https://user-images.githubusercontent.com/4346395/175989306-78830a58-d6e7-4e82-afe8-780768d3f42d.png)

2022-06-27 16:46 UTC, garbageslam commented on account-keys/src/account_keys.rs
> +    fn partial_cmp(&self, other: &ViewAccountKey) -> Option<Ordering> {
I think it may be marginally better to implement partial ord by calling ord, since if partial ord and ord disagree it's a bug

https://doc.rust-lang.org/std/cmp/trait.PartialOrd.html#how-can-i-implement-partialord

2022-06-27 16:47 UTC, garbageslam commented on account-keys/src/account_keys.rs
> +        )
may be worth testing one of the subaddresses of index other than 0 also?

2022-06-27 16:47 UTC, garbageslam approved these changes
LGTM except for nits, thanks for doing this

2022-06-27 17:51 UTC, BrianCorbin commented on account-keys/src/account_keys.rs
> +    fn partial_cmp(&self, other: &ViewAccountKey) -> Option<Ordering> {
Updated this to use cmp, and also updated for AccountKey PartialOrd

2022-06-27 18:07 UTC, jcape commented
This needs to go to master.

2022-06-27 18:11 UTC, remoun requested changes

2022-06-27 18:11 UTC, remoun commented on account-keys/src/account_keys.rs
> +        assert_eq!(account_key.subaddress(500), view_account_key(500));
Seems to be missing the method name.
```suggestion
        assert_eq!(account_key.subaddress(500), view_account_key.subaddress(500));
```

2022-06-27 18:26 UTC, garbageslam commented on account-keys/src/account_keys.rs
> +impl Eq for ViewAccountKey {}
I guess I disagree: we are comparing the Public address which contains all the data, and the point of doing this at all is to be compatible with hash sets and btree sets etc which require such traits

2022-06-28 16:58 UTC, garbageslam commented
Otherwise lgtm still

2022-06-29 21:14 UTC, garbageslam approved these changes
LGTM

2022-06-29 21:24 UTC, remoun approved these changes

2022-06-29 21:24 UTC, remoun commented on account-keys/src/account_keys.rs
> +    pub fn random<T: RngCore + CryptoRng>(rng: &mut T) -> Self {
Optional/Equivalent: Use `impl` instead of generics
```suggestion
    pub fn random(rng: &mut (impl RngCore + CryptoRng)) -> Self {
```

2022-06-29 21:28 UTC, merged