adding block version to create_output
mobilecoinfoundation/mobilecoin pull request #2241
Opened 2022-07-11 20:48 UTC by BrianCorbin

Fixing a bug found while bootstrapping a ledger. Block Version wasn't being passed into the create_output function, which was causing it to fail if setting max-token-id > 0

2022-07-11 21:25 UTC, remoun approved these changes

2022-07-14 14:53 UTC, garbageslam requested changes
I think we should remove the max token id stuff

2022-07-14 17:45 UTC, BrianCorbin commented
> 

Should it just generate all available token ids?

2022-07-14 17:47 UTC, garbageslam commented
https://github.com/mobilecoinfoundation/mobilecoin/pull/2195

2022-07-14 17:50 UTC, garbageslam commented
I added this max token id. stuff when I was trying to figure out how to deploy and test the confidential token id stuff. The idea was to bootstrap the custom tokens and make fog distro able to distribute them. I never got it to actually work and the iteration cycles were pretty long.

The way we actually test the confidential token ids in CD today matches how they come to exist in real life -- we configure governors and mint them. The mobilecoind-dev-faucet is able to distribute the tokens to SDKs after that, or use one of the mobilecoind drain accounts scripts.

I don't see that there is any use case for this flag now, I meant to delete it but it wasn't urgent. Do you have an actual use case or you are just fixing it because it's broken?

2022-07-14 17:52 UTC, garbageslam commented
Christian also had that other PR exposing this flag in more places but again I was trying to say, let's just delete it unless someone can explain what it's good for

2022-07-14 17:55 UTC, garbageslam commented
It probably also breaks the mint auditor because I don't think the mint auditor expects any custom tokens to be bootstrapped (cc @eranrund )

2022-07-14 21:41 UTC, BrianCorbin commented
I have a use case for it. Spinning up a local instance with multiple tokens without having to go through a minting process.

2022-07-14 22:56 UTC, garbageslam commented
Okay, sounds good to me

2022-07-14 22:56 UTC, garbageslam approved these changes

2022-07-15 00:37 UTC, eranrund commented
> It probably also breaks the mint auditor because I don't think the mint auditor expects any custom tokens to be bootstrapped (cc @eranrund )

Yup, the mint auditor would flag them as minted without a matching configuration.

2023-02-28 17:40 UTC, closed without merging