URIs for Fog Ledger Router
mobilecoinfoundation/mobilecoin pull request #2897
Opened 2022-11-23 04:18 UTC by awygle

Add new URIs for Fog Ledger / Key Image Router and Store.

### Motivation

The new Fog Ledger Router and its Key Image Store require two new URI types to exist, one for admin access to the Fog Ledger Router which can add new shards, and one for Key Image Store which will be communicated with by the router.

### Future Work

I don't think there is any future work for this particular PR.

2022-11-23 04:18 UTC, awygle commented
Current dependencies on/for this PR:
* feature/fog-ledger-router
  * **PR #2889** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/2889" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #2891** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/2891" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #2896** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/2896" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #2897** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/2897" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/mobilecoin/2897?utm_source=stack-comment).

2022-11-23 20:42 UTC, nick-mobilecoin approved these changes

2022-11-28 20:10 UTC, samdealy requested changes
While working on removing the legacy Fog View API and updating all the tests, I realized that we don't need to make a specific admin URL for FogViewRouter. Instead, we can just used the existing mc-connection `Admin` url. (I implemented this change [here](https://github.com/mobilecoinfoundation/mobilecoin/pull/2852/commits/9432cb7e1d330d016d0ee40b780c8d545c0eff9d)).

As such, I'd recommend ditching this PR and just updating your tests to use the existing Admin scheme, unless you have a compelling reason to do otherwise.

2022-11-30 18:55 UTC, awygle commented on fog/uri/src/lib.rs
> +impl UriScheme for KeyImageStoreScheme {
Yes, but Fog Ledger supports multiple services (merkle proof service, key image service, block service, untrusted tx out service), and we've only implemented the key image service in this PR series. There was some discussion with @jcape when we first started this about whether to implement unified `FogLedgerStore`s or to separate them by service, which I don't think we really resolved. In general we tried to use `Ledger` terminology for the `Router`, and `KeyImage` terminology for the `Store`.

2022-11-30 18:56 UTC, awygle commented on fog/uri/src/lib.rs
> +            "insecure-key-image-store://node1.test.mobilecoin.com:3223/",
I don't see that as very likely? But if you're suggesting it should be `insecure-fog-key-image-store`, I don't have a problem with making that change.

2022-11-30 18:58 UTC, awygle commented
> While working on removing the legacy Fog View API and updating all the tests, I realized that we don't need to make a specific admin URL for FogViewRouter. Instead, we can just used the existing mc-connection `Admin` url. (I implemented this change [here](https://github.com/mobilecoinfoundation/mobilecoin/pull/2852/commits/9432cb7e1d330d016d0ee40b780c8d545c0eff9d)).
> 
> As such, I'd recommend ditching this PR and just updating your tests to use the existing Admin scheme, unless you have a compelling reason to do otherwise.

I don't think this implies ditching this PR (we still need store URIs), but I'm certainly fine to use the existing Admin scheme for the Admin endpoints. I agree there's no need to introduce redundancy. I'll pull in your Admin changes from the linked commit.

2022-11-30 20:04 UTC, nick-mobilecoin commented on fog/uri/src/lib.rs
> +            "insecure-key-image-store://node1.test.mobilecoin.com:3223/",
I think it's fine, the mc-admin is re-used for all services so those would collide as well.

2022-12-02 19:02 UTC, samdealy approved these changes

2022-12-14 18:04 UTC, jcape approved these changes

2022-12-14 21:17 UTC, merged