Key image store service and server for router/store system
mobilecoinfoundation/mobilecoin pull request #2954
Opened 2022-12-14 01:21 UTC by NotGyro

Implements the `KeyImageStoreApi` GRPC trait for the existing `KeyImageService` type, adds `KeyImageStoreServer`, adds a test for the key image store, and a key image store server binary.

### Motivation
This implements the service (and grpc server to run it) for the Store part of the router/store system.

### Future Work
Tests currently failing which is why this PR is a draft - working of finding the issue, possibly changes need to be pulled in from Main. Particularly, `direct_key_image_store_check`, which directly tests the new behavior added in this PR, is failing with a `ReportVerification(BadSignature)` error.

2023-01-27 04:28 UTC, nick-mobilecoin requested changes
Main blockers are there appear to be extraneous files that aren't needed.

2023-01-27 04:28 UTC, nick-mobilecoin commented on fog/ledger/server/tests/store_tests.rs
> +    let query: EnclaveMessage<NonceSession> = multi_query.pop().unwrap();
:upside_down_face: 
```suggestion
    let query = multi_query.pop().expect("Query should have had one message");
```

2023-01-27 04:28 UTC, nick-mobilecoin commented on fog/ledger/server/tests/store_tests.rs
> +    assert!(test_results.contains(&(test_key_image.key_image, 1)));
:wrench: Suggest comparing to a slice. It provides nicer output on failures and ensures both the length and contents
```suggestion
    let test_results = done_response
        .results
        .into_iter()
        .map(|result| (result.key_image, result.key_image_result_code))
        .collect::<Vec<_>>();

    // The key image result code for a spent key image is 1.
    assert_eq!(test_results, &[(test_key_image.key_image, 1)]);
```

2023-01-27 04:28 UTC, nick-mobilecoin commented on fog/ledger/server/tests/store_tests.rs
> +    report_cache_thread.stop().unwrap();
:wrench: This happens on `drop()`
```suggestion
```
(suggestion will require other changes to compile)

2023-02-02 01:18 UTC, NotGyro commented on fog/ledger/server/Cargo.toml
> +mc-util-keyfile = { path = "../../../util/keyfile" }
Correct, this is a consequence of leaving in things I was using for my initial implementation of `direct_key_image_store_check`, which I later learned were unnecessary. Committing your removal here.

2023-02-02 20:06 UTC, NotGyro commented on fog/ledger/server/src/bin/key_image_store.rs
> +    let mut store_server = KeyImageStoreServer::new_from_config(
The places elsewhere, the `Ledger Store` naming, should be changed. Per Andrew we're going with `Ledger Router` and `Key Image Store.`

2023-02-06 04:48 UTC, NotGyro commented on fog/ledger/server/src/config.rs
> +/// Uri for any node in the key image store system.
Per James and Andrew, this won't be much of a problem when a further refactor takes place to remove support for the old single-server architecture.

2023-02-06 20:03 UTC, jcape approved these changes
LGTM pending other comments to be fixed.

2023-02-06 20:58 UTC, nick-mobilecoin approved these changes
LGTM Thanks!

2023-02-07 01:18 UTC, samdealy approved these changes

2023-02-07 01:18 UTC, samdealy commented on fog/ledger/server/src/bin/key_image_store.rs
> +    );
Consider pulling out the two format values into variables and then use the variables inline in the format string.

2023-02-07 01:18 UTC, samdealy commented on fog/ledger/server/src/key_image_service.rs
> +                    // This is debug because there's no requirement on the remote party to trigger
Should this be a debug log?

2023-02-07 01:18 UTC, samdealy commented on fog/ledger/server/tests/store.rs
> +    // Make GRPC client for sending requests.
Should this be removed since there is no client construction here anymore?

2023-02-07 01:18 UTC, samdealy commented on fog/ledger/server/tests/store.rs
> +    .expect("Failed to start IAS client.");
Consider pushing this set up logic into your TestingContext struct's logic.

2023-02-07 01:18 UTC, samdealy commented on fog/ledger/server/tests/store.rs
> +    let untrusted_kiqr = UntrustedKeyImageQueryResponse {
Please rename the `kiqr` to something like `untrusted_response`. The meaning `kiqr` isn't obvious.

2023-02-07 19:33 UTC, merged