Fog Ledger Router integration test
mobilecoinfoundation/mobilecoin pull request #3188
Opened 2023-02-28 18:31 UTC by awygle

### Motivation

The most interesting functionality of the Fog Ledger Router requires some kind of load balancer to be tested. This is an integration test which tests the behavior of the FLR under real-world (ish) conditions, using localhost ports and direct DB access but otherwise fully exercising the APIs.

Closes #2830 .

### Future Work
We need a test for conflicting information coming from stores, but first we need a decision on what the correct response to that is. Since it's an inconsistency in our blockchain (kinda), it should probably throw an error.

[Soundtrack of this PR]()

2023-03-02 22:20 UTC, nick-mobilecoin requested changes
The main blockers are:
- testing [1,4] instead of [1, 5]
- Currently if an assert fails the test stays running.  Adding a drop implementation to the proxy server, which calls stop resolves this runaway test

While not a blocker I'm a bit concerned with continual addition of large integration tests like these. I know there is #3168 which doesn't seem to cover this. We also need to get things done. I spent more time than I care to admit trying to understand all the pieces necessary for these tests to execute. Only time will tell how soon and how  much we trip up on these large tests. But I can't shake the feeling we keep digging the hole deeper.

2023-03-02 22:59 UTC, NotGyro commented on fog/ledger/server/tests/router_integration.rs
> +}
Seconding this here.

2023-03-02 23:02 UTC, NotGyro approved these changes
Looks good to me

2023-03-03 15:31 UTC, nick-mobilecoin commented on fog/ledger/test_infra/src/lib.rs
> +impl ShardProxyServer {
I don't think these tests are providing any assurances about the behavior of a shard with multiple stores. Thus I think this is adding bunch of complexity to the tests with little to no assurances of behavior.

These tests look like they are testing
```mermaid
flowchart  LR
A(Router) --> B(Shard 1)
B --> F[Store A]
B --> G[Store B]
B --> H[Store C]
```
but this `ShardProxyServer` is faking out the shards, so these tests are
```mermaid
flowchart  LR
A(Router) --> B(Fake Shard 1)
B --> F[Store A]
B --> G[Store B]
B --> H[Store C]
```
Generally in testing one uses a test double (fake, mock, stub, etc) at the edges of what's being tested, but this is in the middle of what's being tested.

2023-03-17 15:57 UTC, nick-mobilecoin commented on fog/ledger/server/tests/router_integration.rs
> +}
was updated to use https://docs.rs/tempdir/latest/tempdir/

2023-03-17 16:03 UTC, nick-mobilecoin commented on fog/ledger/server/tests/router_integration.rs
> +    let mut watcher = setup_watcher_db(watcher_db_path.to_path_buf(), logger.clone());
no longer an issue due to refactor

2023-03-17 16:04 UTC, nick-mobilecoin commented on fog/ledger/server/tests/router_integration.rs
> +    _grpc_env: Arc<grpcio::Environment>,
removed

2023-03-17 16:04 UTC, nick-mobilecoin commented on fog/ledger/server/tests/router_integration.rs
> +    _grpc_env: Arc<grpcio::Environment>,
removed

2023-03-17 16:04 UTC, nick-mobilecoin commented on fog/ledger/server/tests/router_integration.rs
> +    _logger: Logger,
_grpc_env was removed

2023-03-17 16:05 UTC, nick-mobilecoin commented on fog/ledger/server/tests/router_integration.rs
> +        assert_eq!(response.results[0].status(), Ok(Some((i / 9) + 1)));
refactored as suggested

2023-03-17 16:05 UTC, nick-mobilecoin commented on fog/ledger/server/tests/router_integration.rs
> +    }
implemented drop for `test_environment`

2023-03-17 16:06 UTC, nick-mobilecoin commented on fog/ledger/server/tests/router_integration.rs
> +    for _ in 1..5 {
changed to `0..n`

2023-03-17 16:08 UTC, nick-mobilecoin commented on fog/ledger/test_infra/src/lib.rs
> +impl ShardProxyServer {
This was discussed offline. The purpose of the test is to test how the Router handles getting replies back from multiple shards. The shard proxy aren't tested directly as they will be implementation specific to the deployment.

2023-03-17 18:14 UTC, awygle commented
`block_range` is there so we can configure stores incorrectly, which we'll need to close #2831 at the very least. So it will be used in a follow-up.

It's both shard overlap and store overlap, when stores are configured correctly stores and shards are configured to the same block range.

2023-03-17 18:14 UTC, merged