Implement Fog Ledger Router
mobilecoinfoundation/mobilecoin pull request #3312
Opened 2023-04-11 21:17 UTC by awygle

### Motivation

This PR contains all of the feature work related to the Fog Ledger Router. Each change has already been independently reviewed on the feature/fog-ledger-router branch, and the branch itself has been kept up-to-date with master.

2023-04-17 18:15 UTC, samdealy approved these changes

2023-04-19 20:37 UTC, nick-mobilecoin requested changes
The main blocker is `tempdir` shouldn't come back into the mainline

I'm also curious if there is any discussion the `chain_id` validation for the router, shards, and stores.

2023-04-20 18:44 UTC, awygle commented on fog/ledger/server/src/key_image_service.rs
> +        client_listen_uri: KeyImageStoreUri,
I'm not actually sure what the deal is here. `chain_id` is present in FVR but only for the "legacy" unary API. It seems to be part of the auth stuff we do for unary but not for streaming. FLR has it for the APIs that didn't get router-ized, but doesn't seem to have preserved it for the unary Key Image API path.

2023-04-20 19:35 UTC, nick-mobilecoin requested changes
Just the cargo lock causing a lot of churn that doesn't seem necessary

2023-04-20 19:35 UTC, nick-mobilecoin commented on Cargo.lock
> +version = "0.5.2"
:wrench: I was hoping most of the cargo lock would get fixed by the `tempdir` removal but there are still 1600+ changes.
Should move this closer to the mainline, something like the following could be done with this branch checked out.
```shell
git checkout origin/master Cargo.lock
cargo check
git add Cargo.lock
git commit -m "Revert unnecessary Cargo.lock changes"
```

2023-04-20 20:00 UTC, nick-mobilecoin approved these changes

2023-04-20 20:08 UTC, nick-mobilecoin commented on fog/ledger/server/src/key_image_service.rs
> +        client_listen_uri: KeyImageStoreUri,
created #3320 to track this.

2023-04-24 18:17 UTC, merged