Enables dcap
mobilecoinfoundation/mobilecoin pull request #3749
Opened 2023-11-28 22:54 UTC by aweis89

### Motivation

### Future Work

[Soundtrack of this PR]()

2023-12-01 18:02 UTC, joekottke requested changes
The `ledger-distribution` check in the `node_hw` entrypoint definitely needs to be added back in, and I'm curious about the resource definitions/amounts.

2023-12-01 18:02 UTC, joekottke commented on .github/workflows/mobilecoin-workflow-dev-deploy.yaml
> -              intel.com/sgx: 2000
Wouldn't we want these to be updated to the new resource definition?  We have lower limits in Dev than we do in Prod.

2024-01-02 21:16 UTC, jgreat requested changes
Some minor clean up on formatting.

Side note  I would love if we could find a automatic yaml linting tool with something like .rc rules so we can standardize.

2024-01-02 21:16 UTC, jgreat commented on .internal-ci/helm/fog-ledger/values.yaml
> +        sgx.intel.com/epc: "512Ki"
so 5000 should be 20Mi size. Probably `20MiB` if it supports proper bytes.

2024-01-02 21:16 UTC, jgreat commented on .internal-ci/helm/fog-ingest/values.yaml
> +    sgx.intel.com/quote-provider: fog-ingest
What does this do? 

`quote-provider` makes me think its the source for getting quotes, so Azure, or Intel endpoint.

2024-01-02 21:16 UTC, jgreat commented on .internal-ci/docker/Dockerfile.bootstrap-tools
> +  && apt-get install -y \
The indents here were purposeful to show that these were options under the `apt-get install` command. It would be nice to have them back.

2024-01-02 22:35 UTC, aweis89 commented
> Some minor clean up on formatting.
> 
> Side note I would love if we could find a automatic yaml linting tool with something like .rc rules so we can standardize.

Ironically I've been using yamlls which does formatting as well, but it actually seems to prefer to double quotes so I needed to turn it off to revert the `"true"` to `'true'` to single quotes

2024-01-03 21:32 UTC, jgreat approved these changes
Will follow up with sgx.intel.com/epc values.

2024-01-05 20:36 UTC, merged