Add testnet-client release script, and update Cargo.toml for rust_dec…
mobilecoinfoundation/mobilecoin pull request #483
Opened 2020-10-01 14:43 UTC by sugargoat

### Motivation

We typically follow written steps to build mobilecoind and the testnet-client for releases. This PR adds a script to consistently build and package for releases.

### In this PR

    * Adds testnet-client build script
    * Fixes rust_decimal powf build issue in testnet-client Cargo.toml
    * Adds a generic script for the package

2020-10-09 18:02 UTC, jcape requested changes
I appreciate the need to re-enable `rust_decimal`'s `std` feature (`core::f64` does not support the APIs that `rust_decimal` needs), but that doesn't require changing the consensus enclave's `Cargo.lock` at all.

Recommend reverting both `Cargo.lock` files to what exists in `master` and doing `cargo clean && cargo build`, then updating git appropriately. As it stands now, it looks like both lock files were deleted and re-created, effectively upgrading all our dependencies at once.

2020-10-28 02:33 UTC, sugargoat commented
@jcape - updated the Cargo.lock to only include rust-decimal changes.

Also removed the testnet-client release scripts, as they can live with the other release scripts in internal.

2020-10-28 02:34 UTC, kylefleming approved these changes

2020-10-28 17:32 UTC, jcape approved these changes

2020-11-06 08:20 UTC, merged