(Draft) Optionally allow change to be sent to a different subaddress
mobilecoinfoundation/mobilecoin pull request #551
Opened 2020-11-03 01:20 UTC by tsegaran

### Motivation

Binance requires that change be sent to a subaddress other than the sender. This is an attempt to retain backwards compatibility while making this possible.

### In this PR
* Add an optional field to the mobilecoind API with a separate subaddress for change

2020-11-03 18:33 UTC, rjwalters commented
I'd love to see a test case added to `/tools/release-tests/mirror-json-test.py` for this as part of the PR...

2020-11-06 17:30 UTC, garbageslam commented on mobilecoind/src/service.rs
> +        println!("!!!! change subaddress = {}", change_subaddress);
this println should likely not be committed?

2020-11-06 17:39 UTC, garbageslam approved these changes
LGTM otherwise

2020-11-06 18:08 UTC, eranrund requested changes
Looks good but have a some styling nits and a request to make the test more thorough. Thank you!

2020-11-06 18:08 UTC, eranrund commented on mobilecoind-json/src/bin/main.rs
> +    match &transfer.change_subaddress {
this should be `if let Some(subaddress) = transfer.change_subaddress {` (maybe with `.as_ref()`)

2020-11-06 18:08 UTC, eranrund commented on mobilecoind-json/src/bin/main.rs
> +    match &transfer.change_subaddress {
Same as above

2020-11-06 18:08 UTC, eranrund commented on mobilecoind/src/service.rs
> +        let change_subaddress = {
I don't think the extra block is needed. this can be `let change_subaddress = if request ... {`

2020-11-06 18:08 UTC, eranrund commented on mobilecoind/src/service.rs
> +            };
Can you add a verification that the change amount is correct? See https://github.com/mobilecoinfoundation/mobilecoin/blob/alternate-change/mobilecoind/src/sync.rs#L378-L384

2020-11-06 21:04 UTC, eranrund approved these changes

2020-11-06 21:57 UTC, merged