Bump rocket from 0.4.5 to 0.4.6
mobilecoinfoundation/mobilecoin pull request #606
Opened 2020-12-16 21:38 UTC by kylefleming

Bumps [rocket](https://github.com/SergioBenitez/Rocket) from 0.4.5 to 0.4.6.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/SergioBenitez/Rocket/releases">rocket's releases</a>.</em></p>
<blockquote>
<h2>Rocket v0.4.6</h2>
<p>See the <a href="https://github.com/SergioBenitez/Rocket/blob/HEAD/CHANGELOG.md">CHANGELOG</a> for more information.</p>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/SergioBenitez/Rocket/blob/v0.4.6/CHANGELOG.md">rocket's changelog</a>.</em></p>
<blockquote>
<h1>Version 0.4.6 (Nov 09, 2020)</h1>
<h2>Core</h2>
<ul>
<li>[<a href="https://github.com/SergioBenitez/Rocket/commit/86bd7c"><code>86bd7c</code></a>] Added default and configurable read/write timeouts:
<code>read_timeout</code> and <code>write_timeout</code>.</li>
<li>[<a href="https://github.com/SergioBenitez/Rocket/commit/c24a96"><code>c24a96</code></a>] Added the <code>sse</code> feature, which <a href="https://api.rocket.rs/v0.4/rocket/response/struct.Stream.html#buffering-and-blocking">enables flushing</a> by returning
<code>io::ErrorKind::WouldBlock</code>.</li>
</ul>
<h2>Docs</h2>
<ul>
<li>Fixed broken doc links in <code>contrib</code>.</li>
<li>Fixed database library versions in <code>contrib</code> docs.</li>
</ul>
<h2>Internal</h2>
<ul>
<li>Updated source code for Rust 2018.</li>
<li>UI tests now use <code>trybuild</code> instead of <code>compiletest-rs</code>.</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/SergioBenitez/Rocket/commit/b4fadae53dd1babb9a3772712b4ba60abc7a308c"><code>b4fadae</code></a> New version: 0.4.6.</li>
<li><a href="https://github.com/SergioBenitez/Rocket/commit/11ec95ef8f7c4824e99bde60827def319bcd79a7"><code>11ec95e</code></a> Update broken doc links in contrib.</li>
<li><a href="https://github.com/SergioBenitez/Rocket/commit/08bf1c5bdb0bee6b0b19cc7914d8e2a1bf16da6f"><code>08bf1c5</code></a> Update scripts.</li>
<li><a href="https://github.com/SergioBenitez/Rocket/commit/86bd7c1008a7ae8fa48fbc61c9fde72f79f4d5ea"><code>86bd7c1</code></a> Allow read/write timeouts to be configured.</li>
<li><a href="https://github.com/SergioBenitez/Rocket/commit/3970783d06ac34e9e7cbcb50c5d79de43f8594a6"><code>3970783</code></a> Fix SSE example, clean-up SSE related code.</li>
<li><a href="https://github.com/SergioBenitez/Rocket/commit/c24a96308b9fa4ba4e1fff33eb53f69dd16cae75"><code>c24a963</code></a> Add support for immediate chunk flushing, SSE.</li>
<li><a href="https://github.com/SergioBenitez/Rocket/commit/7b1995c84af2013bebb34e0e2d1112efec488e7d"><code>7b1995c</code></a> For install Rust nightly in CI script.</li>
<li><a href="https://github.com/SergioBenitez/Rocket/commit/b109d151a687c5ef0d82a23f6bab3e44cb4d8ce3"><code>b109d15</code></a> Fix library versions in database contrib docs.</li>
<li><a href="https://github.com/SergioBenitez/Rocket/commit/6f5725b83d098c9641f5f1a046aded13c250d996"><code>6f5725b</code></a> Update source code idiomacy, clearing warnings.</li>
<li><a href="https://github.com/SergioBenitez/Rocket/commit/894fe3c70912aaeb457355335a897d53a2032ba4"><code>894fe3c</code></a> Fix benchmark features.</li>
<li>Additional commits viewable in <a href="https://github.com/SergioBenitez/Rocket/compare/v0.4.5...v0.4.6">compare view</a></li>
</ul>
</details>
<br />

2020-12-17 06:41 UTC, kylefleming commented
this is deployed as build/82: https://deploybot.canadacentral.mobilecoin.com/job/mobilecoin-internal/job/deploy%252Fbuild/82/

2020-12-17 18:50 UTC, sugargoat approved these changes

2020-12-18 20:00 UTC, jcape approved these changes

2020-12-18 20:01 UTC, jcape requested changes
This and rocket_contrib should be updated together, no?

2020-12-18 22:38 UTC, kylefleming commented
`rocket` and `rocket_contrib` are now both included in this PR.

2020-12-21 22:54 UTC, sugargoat approved these changes

2020-12-24 00:09 UTC, jcape approved these changes

2020-12-24 04:16 UTC, merged