Make an error passable across enclave boundary
mobilecoinfoundation/mobilecoin pull request #710
Opened 2021-02-08 00:01 UTC by garbageslam

This error should derive serde so that it can be passed across enclave boundary

2021-02-09 19:38 UTC, jcape requested changes
This needs to use `serde::{Serialize, Deserialize};`

2022-02-10 22:27 UTC, remoun commented
This PR still seems relevant; do we want to (fix and) merge it?

2022-02-10 22:52 UTC, garbageslam commented
Yea that would be a good thing

2023-10-23 20:05 UTC, nick-mobilecoin commented
Closing it looks like this was done in https://github.com/mobilecoinfoundation/mobilecoin/pull/1658

2023-10-23 20:05 UTC, closed without merging