Add slam tool to consensus server repo
mobilecoinfoundation/mobilecoin pull request #733
Opened 2021-02-23 22:01 UTC by garbageslam

The slam tool is a load testing tool for the consensus servers.
Generally, test code should be versioned with the code under test.

This moves the slam tool to the same repo as the consensus servers,
and will make it easier to run this test in CD and more easily use
it to validate changes to the consensus servers.

2021-02-23 22:37 UTC, eranrund requested changes
Some documentation things need to be improved but we know the code is doing its job :)

2021-02-23 22:37 UTC, eranrund commented on slam/Cargo.toml
> +authors = ["drakeley <sara.drakeley@gmail.com>"]
I believe we just put `MobileCoin` here.

2021-02-23 22:37 UTC, eranrund commented on slam/README.md
> +    internal/target/sample_data $ cargo run --manifest-path=../../public/Cargo.toml -p mc-util-keyfile \
This needs to be updated

2021-02-23 22:37 UTC, eranrund commented on slam/src/config.rs
> +//! Configuration parameters for the slam script
This needs a copyright notice

2021-02-23 23:46 UTC, garbageslam commented
@jcape lmk if the updates for `HardcodedCredentialsProvider` looks right, i mostly copied from `mobilecoind`

Do you guys think the crate should be `mc-slam` now?

2021-02-23 23:54 UTC, jcape commented
> Do you guys think the crate should be `mc-slam` now?

Yep (will review inline for the HCP stuff)

2021-02-24 00:06 UTC, jcape approved these changes
LGTM, assuming it runs properly against deployed networks. I'd remove some of the weird stuff from `README.md`, though, like references to specific networks or repositories that people may not have access to...

2021-02-24 00:28 UTC, garbageslam commented
TODO:
-[] deploy and run slam as in instructions

2021-03-09 04:49 UTC, sugargoat approved these changes

2021-03-09 04:59 UTC, merged