Update our fork of grpc-rs to version 0.9
mobilecoinfoundation/mobilecoin pull request #839
Opened 2021-06-17 00:08 UTC by christian-oudard

* Change API calls to grpc-rs for the new version.
* Upgrade our fork of mbedtls to the most recent version.
* Change memory management of Certificate objects for new version of
  mbedtls.
* Synchronize versions of bindgen between our various forks.

2021-06-18 00:14 UTC, jcape requested changes
Initial round of comments, I'll add more based on CI results / as needed.

2021-06-18 00:14 UTC, jcape commented on mobilecoind/src/service.rs
> +            RpcStatus::with_message(RpcStatusCode::INVALID_ARGUMENT, "account_key".to_string())
Can these all be `"foo".into()` to match the stuff in `consensus/service/src/api/grpc_error.rs` above?

2021-06-18 00:14 UTC, jcape commented on mobilecoind/src/service.rs
> +                "no bootstrap block".to_owned(),
Same as above, would be nice to have a single way to do this.

2021-06-18 00:14 UTC, jcape commented on sgx/core-types-sys/Cargo.toml
> +[package]
This file has been removed, please rebase/merge master to this branch.

2021-06-18 00:14 UTC, jcape commented on util/build/enclave/Cargo.toml
> +mbedtls = { version = "0.8.1", default-features = false, features = ["no_std_deps"] }
Now that we're doing `resolver = "2"`, this can probably just be `mbedtls = "0.8.1"`

2021-06-18 00:14 UTC, jcape commented on util/grpc/src/health_service.rs
> +                "Unimplemented".to_string(),
Same `.to_string()` vs `.to_owned()` vs `.into()` as above.

2021-06-21 22:55 UTC, jcape commented on attest/core/Cargo.toml
> +mbedtls-sys-auto = "2.26.1"
I think this is still applicable

2021-06-22 18:59 UTC, eranrund commented on .circleci/config.yml
> +        default: cargo test --frozen --target "$HOST_TARGET_TRIPLE" --no-fail-fast --tests -j 6
Unfortunately without this the linker runs out of memory :/

2021-06-22 19:20 UTC, jcape requested changes
There need to be additional changes to rust-mbedtls to make this go, I think.

2021-06-22 19:20 UTC, jcape commented on consensus/enclave/trusted/Cargo.lock
> + "rs-libc",
This is going to cause symbol issues with the `sgx_tcalloc`---they're both exporting `malloc`, `free`, & friends as C symbols.

2021-06-22 19:23 UTC, jcape approved these changes

2021-06-24 17:22 UTC, eranrund commented
This passed deployment [here](https://deploybot.development-eu1.mobilecoin.com/blue/organizations/jenkins/mobilecoin-internal/detail/deploy%2Feran/5/pipeline/)

The changes from stock mbedtls can be seen [here](https://github.com/mobilecoinofficial/rust-mbedtls/compare/mc-develop?expand=1).
The changes in `grpcio` can be seen [here](https://github.com/tikv/grpc-rs/compare/master...mobilecoinofficial:client-unary-metadata?expand=1)

2021-06-24 17:41 UTC, sugargoat approved these changes

2021-06-24 17:43 UTC, merged